"""Added KYC to Client

Revision ID: 13a88325ceb4
Revises: aed6b925ced6
Create Date: 2026-02-22 03:56:24.582751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a88325ceb4'
down_revision = 'aed6b925ced6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profession', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nationalite', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('situation_matrimoniale', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('regime_matrimonial', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('forme_juridique', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('capital_social', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('rccm', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ninea', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('type_piece_identite', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('numero_piece_identite', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_emission_piece', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_expiration_piece', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('autorite_emission_piece', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kyc_statut', sa.String(length=20), nullable=False, server_default='A_VERIFIER'))
        batch_op.add_column(sa.Column('kyc_date_verification', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('kyc_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('kyc_notes')
        batch_op.drop_column('kyc_date_verification')
        batch_op.drop_column('kyc_statut')
        batch_op.drop_column('autorite_emission_piece')
        batch_op.drop_column('date_expiration_piece')
        batch_op.drop_column('date_emission_piece')
        batch_op.drop_column('numero_piece_identite')
        batch_op.drop_column('type_piece_identite')
        batch_op.drop_column('ninea')
        batch_op.drop_column('rccm')
        batch_op.drop_column('capital_social')
        batch_op.drop_column('forme_juridique')
        batch_op.drop_column('regime_matrimonial')
        batch_op.drop_column('situation_matrimoniale')
        batch_op.drop_column('nationalite')
        batch_op.drop_column('profession')

    # ### end Alembic commands ###
