"""add account locking fields

Revision ID: 256e0e8e5d40
Revises: 13a88325ceb4
Create Date: 2026-02-26 23:19:59.700682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256e0e8e5d40'
down_revision = '13a88325ceb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_locked')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
