"""fix security logs table structure

Revision ID: 3bfb1c052901
Revises: 9efafc904856
Create Date: 2026-03-01 04:41:47.328283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3bfb1c052901'
down_revision = '9efafc904856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_piece_identite', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('numero_piece_identite', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_emission_piece', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_expiration_piece', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('autorite_emission_piece', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kyc_statut', sa.String(length=20), nullable=False, server_default='A_VERIFIER'))
        batch_op.add_column(sa.Column('kyc_date_verification', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('kyc_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.func.now()))

    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('type_piece_identite')
        batch_op.drop_column('date_expiration_piece')
        batch_op.drop_column('kyc_notes')
        batch_op.drop_column('numero_piece_identite')
        batch_op.drop_column('autorite_emission_piece')
        batch_op.drop_column('date_emission_piece')
        batch_op.drop_column('kyc_date_verification')
        batch_op.drop_column('kyc_statut')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kyc_statut', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('kyc_date_verification', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_emission_piece', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('autorite_emission_piece', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('numero_piece_identite', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kyc_notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_expiration_piece', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type_piece_identite', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('kyc_notes')
        batch_op.drop_column('kyc_date_verification')
        batch_op.drop_column('kyc_statut')
        batch_op.drop_column('autorite_emission_piece')
        batch_op.drop_column('date_expiration_piece')
        batch_op.drop_column('date_emission_piece')
        batch_op.drop_column('numero_piece_identite')
        batch_op.drop_column('type_piece_identite')

    # ### end Alembic commands ###
