"""Add audit fields to SecurityLog

Revision ID: 5e9c749534e5
Revises: c9538b8512b7
Create Date: 2026-03-20 02:55:36.828818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9c749534e5'
down_revision = 'c9538b8512b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_resource', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('target_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('changes', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.drop_column('changes')
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_resource')

    # ### end Alembic commands ###
