"""ajout tables bareme dynamique

Revision ID: 8fde36b06327
Revises: 5e9c749534e5
Create Date: 2026-03-20 04:55:17.465549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fde36b06327'
down_revision = '5e9c749534e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bareme_modeles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('type_acte_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['type_acte_id'], ['type_actes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bareme_modeles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bareme_modeles_code'), ['code'], unique=True)

    op.create_table('bareme_lignes_calcul',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bareme_id', sa.Integer(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=200), nullable=False),
    sa.Column('type_ligne', sa.String(length=30), nullable=False),
    sa.Column('condition_affichage', sa.Text(), nullable=True),
    sa.Column('formule_ou_montant', sa.Text(), nullable=True),
    sa.Column('tranches_json', sa.JSON(), nullable=True),
    sa.Column('soumis_tva', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bareme_id'], ['bareme_modeles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bareme_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bareme_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('type_champ', sa.String(length=20), nullable=False),
    sa.Column('choix_json', sa.JSON(), nullable=True),
    sa.Column('valeur_defaut', sa.String(length=200), nullable=True),
    sa.Column('requis', sa.Boolean(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bareme_id'], ['bareme_modeles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bareme_variables')
    op.drop_table('bareme_lignes_calcul')
    with op.batch_alter_table('bareme_modeles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bareme_modeles_code'))

    op.drop_table('bareme_modeles')
    # ### end Alembic commands ###
