"""add security logs table

Revision ID: 9efafc904856
Revises: aa4e4357dbea
Create Date: 2026-03-01 04:32:49.621010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9efafc904856'
down_revision = 'aa4e4357dbea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('type_piece_identite', sa.String(length=50), nullable=True),
    sa.Column('numero_piece_identite', sa.String(length=100), nullable=True),
    sa.Column('date_emission_piece', sa.Date(), nullable=True),
    sa.Column('date_expiration_piece', sa.Date(), nullable=True),
    sa.Column('autorite_emission_piece', sa.String(length=100), nullable=True),
    sa.Column('kyc_statut', sa.String(length=20), nullable=False),
    sa.Column('kyc_date_verification', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('kyc_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('autorite_emission_piece')
        batch_op.drop_column('kyc_statut')
        batch_op.drop_column('date_expiration_piece')
        batch_op.drop_column('numero_piece_identite')
        batch_op.drop_column('created_at')
        batch_op.drop_column('kyc_date_verification')
        batch_op.drop_column('date_emission_piece')
        batch_op.drop_column('type_piece_identite')
        batch_op.drop_column('kyc_notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kyc_notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type_piece_identite', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_emission_piece', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kyc_date_verification', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('numero_piece_identite', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_expiration_piece', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kyc_statut', sa.VARCHAR(length=20), server_default=sa.text("'A_VERIFIER'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('autorite_emission_piece', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    op.drop_table('security_logs')
    # ### end Alembic commands ###
