"""add parametres_etude table

Revision ID: aed6b925ced6
Revises: c857b667fa5a
Create Date: 2026-02-21 21:50:43.023802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed6b925ced6'
down_revision = 'c857b667fa5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametres_etude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cle', sa.String(length=100), nullable=False),
    sa.Column('valeur', sa.Text(), nullable=False),
    sa.Column('type_valeur', sa.String(length=20), nullable=False),
    sa.Column('groupe', sa.String(length=30), nullable=False),
    sa.Column('libelle', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parametres_etude', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parametres_etude_cle'), ['cle'], unique=True)

    op.drop_table('compta_baremes')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.alter_column('is_docx',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.alter_column('is_docx',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    op.create_table('compta_baremes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_acte_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('libelle', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('categorie', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('mode', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('valeur', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('base_calcul', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('seuil_min', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('seuil_max', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('ordre', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['type_acte_id'], ['type_actes.id'], name=op.f('compta_baremes_type_acte_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('compta_baremes_pkey'))
    )
    with op.batch_alter_table('parametres_etude', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parametres_etude_cle'))

    op.drop_table('parametres_etude')
    # ### end Alembic commands ###
