"""Add TypeActe and update Template/Acte

Revision ID: c857b667fa5a
Revises: 4d4ca8ff7936
Create Date: 2025-12-19 02:09:27.573483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c857b667fa5a'
down_revision = '4d4ca8ff7936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_actes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    with op.batch_alter_table('actes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_acte_id', sa.Integer(), nullable=True))
        batch_op.alter_column('contenu_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'type_actes', ['type_acte_id'], ['id'])

    with op.batch_alter_table('compta_comptes', schema=None) as batch_op:
        batch_op.alter_column('actif',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.alter_column('montant_tva',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'IMPAYEE'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        # Use raw SQL for conditional drop
        op.execute('DROP INDEX IF EXISTS idx_factures_client')
        op.execute('DROP INDEX IF EXISTS idx_factures_date')
        op.execute('DROP INDEX IF EXISTS idx_factures_dossier')
        op.execute('DROP INDEX IF EXISTS idx_factures_statut')

    with op.batch_alter_table('recus', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        # Use raw SQL for conditional drop
        op.execute('DROP INDEX IF EXISTS idx_recus_client')
        op.execute('DROP INDEX IF EXISTS idx_recus_date')
        op.execute('DROP INDEX IF EXISTS idx_recus_dossier')

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_acte_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'type_actes', ['type_acte_id'], ['id'])
        batch_op.drop_column('type_acte')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_acte', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('type_acte_id')

    with op.batch_alter_table('recus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_recus_dossier'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_recus_date'), ['date_emission'], unique=False)
        batch_op.create_index(batch_op.f('idx_recus_client'), ['client_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_factures_statut'), ['statut'], unique=False)
        batch_op.create_index(batch_op.f('idx_factures_dossier'), ['dossier_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_factures_date'), ['date_emission'], unique=False)
        batch_op.create_index(batch_op.f('idx_factures_client'), ['client_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'IMPAYEE'::character varying"))
        batch_op.alter_column('montant_tva',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('compta_comptes', schema=None) as batch_op:
        batch_op.alter_column('actif',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('actes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('contenu_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_column('type_acte_id')

    op.drop_table('type_actes')
    # ### end Alembic commands ###
